### ISSUE TITLE
Closes as soon as i click continue.

### ISSUE THREAD

**Issue by TechinicFiles** [Aceba1/TerraTech-Mod-Manager#2]
The title is pretty self explanatory. I click open, get to the main screen, then it crashes. Its opened as an administrator.

**Comment by Aceba1** [comment]
Does it show a popup with the exception, or simply stop working?
oh wow, sorry for being *over 2 months late...*

**Comment by Austin5003** [comment]
I've had the same issue because I installed the mod manager from the nexus website
You just have to uninstall that and run the mod manager executable again, then it will run

**Comment by tanker122** [comment]
i've been having trouble getting the mod manager to open, i put in my path (i have two hard drives) and i click continue and it says "webpage cannot be reached" and it gives me an mp4 file

**Comment by Aceba1** [comment]
@tanker122 Have you tried verifying your game file integrity, or re-installing the game?

**Comment by HeXaNi** [comment]
> i've been having trouble getting the mod manager to open, i put in my path (i have two hard drives) and i click continue and it says "webpage cannot be reached" and it gives me an mp4 file

Have you tried not using a pirated version of the game? Try buying the game and supporting the devs! I heard it fixes the issue.

**Comment by HeX-Boi** [comment]
> i've been having trouble getting the mod manager to open, i put in my path (i have two hard drives) and i click continue and it says "webpage cannot be reached" and it gives me an mp4 file

Have you tried not using a pirated version of the game? Perhaps you should get the game first. That'd probably help a _bit_

**Comment by Mindlessmrawesome** [comment]
> i've been having trouble getting the mod manager to open, i put in my path (i have two hard drives) and i click continue and it says "webpage cannot be reached" and it gives me an mp4 file

Yeah, whitepaw made a piracy detector. It plays a video telling you not to pirate games. If you got a legit version of the game something's wrong with your files, so verifying the integrity of your files (done by right-clicking the game in the steam menu, then going down to properties, then going to the "local files" tab in the window that opens, then clicking "verify integrity of game files") should fix it. If you DON'T have a legit copy of the game, then I suggest you get one if you want mods.

**Comment by tanker122** [comment]
i didn't pirate the game, i have no way of downloading steam or the room too on my hard drives with how my computer is set up,so i used smart steam emu to play my steam games. but thank you ^^

**Comment by Aceba1** [comment]
I was unaware that there is such a thing as a steam emulator. I am sorry for the inconvenience, as I do not know how this system works either.
